# Generated by Django 5.1.7 on 2025-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_address', models.TextField()),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
